name: Build Typst and deploy to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Download Typst release
        run: |
          release="typst-x86_64-unknown-linux-musl"
          curl -L -o typst.tar.xz "github.com/typst/typst/releases/download/v0.15.1/$release.tar.xz"  
          tar -xJf typst.tar.xz
          mv "$release/typst" .
          chmod +x typst
          ./typst --version
      - name: Typst build
        run: ./typst compile --features=bundle,html --format=bundle index.typ
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
